name = "DevNetAr"
license = "MIT"
description = "A minimal Hugo theme"
homepage = "https://github.com/maurogabriel/hugo-theme-devnetar"
tags = ["blog", "minimal", "simple", "clean"]
features = ["blog"]

[author]
    name = "Mauro Gabriel"
    homepage = "http://maurogabriel.com.ar"
